---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: bucket
  namespace: flux-system
spec:
  force: true
  refreshBeforeApply: true
  path: ./
  sourceRef:
    kind: Bucket
    name: dev-bucket
  approvePlan: auto
  interval: 1m
  destroyResourcesOnDeletion: true