apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: flux-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_REGION: us-east-1 # the region you want
  TF_AWS_DYNAMODB_ENDPOINT: "http://localstack.svc.cluster.local"
  TF_AWS_S3_ENDPOINT: "http://localstack.svc.cluster.local"
  TF_AWS_STS_ENDPOINT: "http://localstack.svc.cluster.local"
  TF_AWS_IAM_ENDPOINT: "http://localstack.svc.cluster.local"
  TF_S3_FORCE_PATH_STYLE: "true"
  TF_SKIP_CREDENTIALS_VALIDATION: "true"
  TF_SKIP_METADATA_API_CHECK: "true"
  TF_SKIP_REQUESTION_ACCOUNT_ID: "true"