---
apiVersion: v1
kind: Secret
metadata:
  name: aws-account-creds
  namespace: crossplane-system
type: Opaque
data:
  key: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gJ3Rlc3QnCmF3c19zZWNyZXRfYWNjZXNzX2tleSA9ICd0ZXN0Jwo=

# aws_access_key_id= test
# aws_secret_access_key = test
# echo -e "[default]\naws_access_key_id = 'test'\naws_secret_access_key = 'test'" | base64  | tr -d "\n"  