---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: telegraf
  namespace: flux-system
spec:
  chart:
    spec:
      chart: telegraf
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: influxdb
  values:
    service:
      enabled: true
      type: ClusterIP
      annotations: {}
    config:
      agent:
        interval: 60s
        round_interval: true
        metric_batch_size: 1000000
        metric_buffer_limit: 100000000
        collection_jitter: 0s
        flush_interval: 60s
        flush_jitter: 0s
        precision: ''
        omit_hostname: false
      inputs:
        - http_listener_v2:
            service_address: ":8080"
            data_format: "prometheusremotewrite"
            path: "/receive"
      outputs:
        - influxdb_v2:
            token: "1234567890qwerty"
            organization: "influxdata"
            bucket: default
            urls:
              - "https://influxdb.svc.cluster.local:8086"
  interval: 1m0s
# https://github.com/influxdata/helm-charts/blob/master/charts/telegraf/values.yaml
# https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http_listener_v2
# https://github.com/influxdata/telegraf/tree/master/plugins/parsers/prometheusremotewrite
# https://github.com/influxdata/telegraf/tree/master/plugins/outputs/influxdb_v2