---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/tenant: infra-team
spec:
  interval: 30m
  chart:
    spec:
      chart: tf-controller
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
      interval: 65m
# https://github.com/weaveworks/tf-controller/blob/main/charts/tf-controller/values.yaml
