---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  interval: 10m
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: kyverno-policies
      version: "2.6.1"
      sourceRef:
        kind: HelmRepository
        name: kyverno-policies
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace